series: Basic OpenGL with GLFW
title: Normal Maps
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Add increased lighting detail to geometry using normal maps.
language: C++
tags:
  - Graphics
  - Math
extra_resources:
  - link: http://ogldev.atspace.co.uk/www/tutorial26/tutorial26.html
    title: An in depth explanation of the math involved for those interested.
connections:
  - series: Basic OpenGL with GLFW
    title: Object Loading